# Generated by Django 3.0.5 on 2020-09-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=300)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(max_length=5000)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
