# Generated by Django 3.0.5 on 2020-09-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone_num',
        ),
    ]
